### PR TITLE
Roll in the rest of the MCA infrastructure, including heterogeneous o…

### PR DESCRIPTION
**Pull request by rhc54**
…perations support, dlopen, and security frameworks

Almost all compiling now

remove ignores

Minor touchups

Remove stale component

installdirs: remove generated file

This .h file is generated and should not be in the repo.

Signed-off-by: Jeff Squyres <jsquyres@cisco.com>

keyval: have Automake descend into src/util/keyval

Need to have Automake descend into this directory in order to re-build
the lex file and then compile it.

Signed-off-by: Jeff Squyres <jsquyres@cisco.com>

configure.ac: fix typo

Signed-off-by: Jeff Squyres <jsquyres@cisco.com>

configury: fix off-by-one variable indexing

The MCA system in this tree uses fewer params for the component
COMPILE_MODE macros, so reduce each variable index by 1.

Signed-off-by: Jeff Squyres <jsquyres@cisco.com>

Everything now builds. However, install fails if run as non-root due to attempt to install Perl modules in a non-prefix location

### CODE REVIEW

**Comment by rhc54** [comment]
@gmkurtzer This is ready to bring across. However, as my note at the end indicates, ```make install``` fails when run as non-root because you setup the Perl modules to install into a root-level directory instead of the prefix location. Is there some reason for doing this? I didn't change it pending your answer.

**Comment by gmkurtzer** [comment]
Fantastic, I'm looking forward to playing with it. The Perl modules go into
the standard Perl location where modules should go so they can be found by
the default Perl. I'm open to options.

-- 
Gregory M. Kurtzer
High Performance Computing Services (HPCS)
University of California
Lawrence Berkeley National Laboratory
One Cyclotron Road, Berkeley, CA 94720

**Comment by rhc54** [comment]
I see - it just means that you can only install this as root, which is somewhat unexpected to me. I believe there is a way to tell Perl an alternate location for modules, yes? Would provide a cleaner solution that maintained separation and kept the Perl and C libs under the same location.

I'm still seeing a build issue on this branch when I check it out from scratch - not getting the compile to descend properly into some locations. Investigating.

**Comment by gmkurtzer** [comment]
Yes you are right, you can include the appropriate path into @INC, and it
will work just fine. But that means we need to hard code it in the calling
script or have a wrapper which can set it.

In either case, I will find an option so it doesn't have to be installed as
root.




-- 
Gregory M. Kurtzer
High Performance Computing Services (HPCS)
University of California
Lawrence Berkeley National Laboratory
One Cyclotron Road, Berkeley, CA 94720

**Comment by rhc54** [comment]
Hmmm...why not just have configure put the ```@INC``` into the installed scripts? Your talking about things like ```wwsh```, yes? Should be easy enough to do.

**Comment by gmkurtzer** [comment]
Yep, that is what I have done in the past but it means that perldocs, and
other generalized scripts will need to be customized to "use" Warewulf. Not
an end game by any means, but also not as clean as I would prefer. But it
is probably cleaner then forcing a root level install. Lol

-- 
Gregory M. Kurtzer
High Performance Computing Services (HPCS)
University of California
Lawrence Berkeley National Laboratory
One Cyclotron Road, Berkeley, CA 94720

**Comment by jmstover** [comment]
Why not put like a ${HOME}/.wwenv  or something, which sets PERL5LIB to include the install dir?

Or at the end of the make print out a big message about it with:

If you installed non-root you must be sure to include the path in PERL5LIB:
  export PERL5LIB @perl5lib@ 

Or whatever ...

**Comment by gmkurtzer** [comment]
Good suggestions!

**Comment by rhc54** [comment]
@gmkurtzer This is now good to go!

**Comment by gmkurtzer** [comment]
Thanks Ralph, I will play with this later today!

**Pull request merged**
